module.exports = {
    firstName: 'Isaac',
    lastName: 'Lopez',
    email: 'isaac.lopez.5xqxzeas@mailosaur.io',
    postalCode: '64440',
    city: 'Monterrey',
    country: 'Mexico',
    message: 'This is a test message generated by automated script.'
};
